# Generated by Django 2.2.15 on 2020-08-31 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('description', models.TextField()),
                ('fileName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageType', models.TextField()),
                ('pageTitle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DevPersonalPage',
            fields=[
                ('personalpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PersonalPage')),
                ('expectedGraduationYear', models.IntegerField()),
                ('biography', models.TextField()),
                ('motivationForWorking', models.TextField()),
                ('contributions', models.ManyToManyField(to='core.Contribution')),
            ],
            bases=('core.personalpage',),
        ),
    ]
