# Generated by Django 2.2.15 on 2020-08-31 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorPersonalPage',
            fields=[
                ('personalpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PersonalPage')),
                ('missionStatement', models.TextField()),
                ('reasonForSponsorship', models.TextField()),
                ('companyLink', models.TextField()),
            ],
            bases=('core.personalpage',),
        ),
    ]
