# Generated by Django 2.2.16 on 2020-09-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_log_robot_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='_comment_replies_+', to='core.Comment'),
        ),
        migrations.AlterField(
            model_name='devpersonalpage',
            name='contributions',
            field=models.ManyToManyField(blank=True, to='core.Contribution'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='comments',
            field=models.ManyToManyField(blank=True, to='core.Comment'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='headings',
            field=models.ManyToManyField(blank=True, to='core.Heading'),
        ),
        migrations.AlterField(
            model_name='heading',
            name='subHeadings',
            field=models.ManyToManyField(blank=True, related_name='_heading_subHeadings_+', to='core.Heading'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='entries',
            field=models.ManyToManyField(blank=True, to='core.Entry'),
        ),
    ]
