# Generated by Django 2.2.16 on 2020-09-09 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200909_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='page',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.PersonalPage'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sideBar',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.SideBar'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='page',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.PersonalPage'),
        ),
    ]
