# Generated by Django 2.2.16 on 2020-10-01 01:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201001_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
