# Generated by Django 2.2.16 on 2020-10-06 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201001_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
    ]
