# Generated by Django 2.2.16 on 2020-10-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201006_2346'),
        ('core', '0007_auto_20201007_0355'),
    ]

    operations = [
    ]
