# Generated by Django 2.2.16 on 2020-11-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_accountlevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'get_latest_by': 'dateTime'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'get_latest_by': 'log'},
        ),
    ]
