# Generated by Django 2.2.19 on 2021-03-06 15:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201115_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='robots',
        ),
        migrations.RemoveField(
            model_name='log',
            name='robot',
        ),
        migrations.RemoveField(
            model_name='log',
            name='run',
        ),
        migrations.AddField(
            model_name='log',
            name='deviceID',
            field=models.TextField(default='NotSet'),
        ),
        migrations.AddField(
            model_name='log',
            name='filePath',
            field=models.TextField(default='NotSet'),
        ),
        migrations.AddField(
            model_name='log',
            name='runs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default="{default: 'default'}"),
        ),
        migrations.DeleteModel(
            name='Robot',
        ),
        migrations.DeleteModel(
            name='Run',
        ),
    ]
