# Generated by Django 2.2.19 on 2021-03-06 15:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210306_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='runs',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
