# Generated by Django 2.2.19 on 2021-03-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210306_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='runs',
        ),
    ]
