# Generated by Django 2.2.19 on 2021-03-17 23:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_log_runs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('deviceID', models.TextField(default='NotSet')),
                ('runID', models.IntegerField(default='NotSet')),
                ('run', django.contrib.postgres.fields.jsonb.JSONField()),
                ('logID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Log')),
            ],
        ),
    ]
