# Generated by Django 3.1.7 on 2021-04-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='run',
            field=models.JSONField(),
        ),
    ]
