version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn  -w 4 --bind 0.0.0.0:8000 swarm_backend.wsgi
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod

  nginx:
    image: nginx:latest
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/build

networks:
  default:
    external:
      name: swarm-net

volumes:
  build_folder:
    external: true
    name: swarm-website-frontend_build_folder