services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn  -w 4 --bind 0.0.0.0:8000 swarm_backend.wsgi
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

networks:
  default:
    external:
      name: swarm-net

volumes:
  postgres_data:
  static_volume: