  version: '3'

  services:
    web:
      build: .
      #-w adds workers, 4 for now but we can add if server traffic warrants it
      command: gunicorn -w 4 --bind 0.0.0.0:8000 swarm_backend.wsgi
      volumes:
        - .:/code
      ports:
        - "8000:8000"
  networks:
    default:
      external:
        name: swarm-net
